// <auto-generated />
using System;
using Fraud.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fraud.Infrastructure.Migrations
{
    [DbContext(typeof(FraudDbContext))]
    [Migration("20260213102411_InitialFraudModule")]
    partial class InitialFraudModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fraud")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fraud.Domain.Entities.CardFraudProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentRiskScore")
                        .HasColumnType("int");

                    b.Property<int>("DeclinedTransactionCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstTransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Last1HourTxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Last1HourTxCount")
                        .HasColumnType("int");

                    b.Property<int>("Last24HourDistinctCountryCount")
                        .HasColumnType("int");

                    b.Property<int>("Last24HourDistinctMerchantCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Last24HourTxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Last24HourTxCount")
                        .HasColumnType("int");

                    b.Property<int>("Last7DayTxCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastFraudAlertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastMerchantId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastTransactionCountry")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("LastTransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaskedCardNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalFraudConfirmedCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalHitScenarioCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalTransactionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTransactionCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRiskScore");

                    b.HasIndex("MaskedCardNo")
                        .IsUnique();

                    b.ToTable("CardFraudProfiles", "fraud");
                });

            modelBuilder.Entity("Fraud.Domain.Entities.FraudAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CardStatusAction")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CardStatusReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<Guid>("FraudAlertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaskedCardNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FraudAlertId");

                    b.HasIndex("MaskedCardNo");

                    b.HasIndex("TransactionId");

                    b.ToTable("FraudActions", "fraud");
                });

            modelBuilder.Entity("Fraud.Domain.Entities.FraudAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("Decision")
                        .HasColumnType("int");

                    b.Property<string>("HighestFraudResponseCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("HitScenarioCount")
                        .HasColumnType("int");

                    b.Property<string>("MaskedCardNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MerchantId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<decimal>("TransactionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MaskedCardNo");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("FraudAlerts", "fraud");
                });

            modelBuilder.Entity("Fraud.Domain.Entities.FraudBlacklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlacklist")
                        .HasColumnType("bit");

                    b.Property<string>("ListType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ListType", "Value")
                        .IsUnique();

                    b.HasIndex("ListType", "IsBlacklist", "IsActive");

                    b.ToTable("FraudBlacklists", "fraud");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            IsBlacklist = true,
                            ListType = "Country",
                            Reason = "Kuzey Kore — yaptırım ülkesi",
                            Value = "KP"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            IsBlacklist = true,
                            ListType = "Country",
                            Reason = "İran — yaptırım ülkesi",
                            Value = "IR"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            IsBlacklist = true,
                            ListType = "Country",
                            Reason = "Suriye — yaptırım ülkesi",
                            Value = "SY"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            IsBlacklist = true,
                            ListType = "MCC",
                            Reason = "Kumar — yüksek riskli MCC",
                            Value = "7995"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            IsBlacklist = true,
                            ListType = "MCC",
                            Reason = "Doğrudan pazarlama — yüksek riskli",
                            Value = "5967"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            IsActive = true,
                            IsBlacklist = false,
                            ListType = "Country",
                            Reason = "Türkiye — beyaz liste (yerli işlem)",
                            Value = "TR"
                        });
                });

            modelBuilder.Entity("Fraud.Domain.Entities.FraudRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LogicalOperator")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PeriodFunction")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PeriodGroupBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PeriodMinutes")
                        .HasColumnType("int");

                    b.Property<decimal?>("PeriodThreshold")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RuleType")
                        .HasColumnType("int");

                    b.Property<string>("SqlScript")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("FraudRules", "fraud");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            Code = "R001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "Tek işlem tutarı 25.000 TL üzeri",
                            IsActive = true,
                            LogicalOperator = 1,
                            Name = "Yüksek Tutarlı İşlem",
                            RuleType = 1
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000002"),
                            Code = "R002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "Yurtdışı işlem + 5.000 TL üzeri",
                            IsActive = true,
                            LogicalOperator = 1,
                            Name = "Yurtdışı Yüksek Tutar",
                            RuleType = 2
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000003"),
                            Code = "R003",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "02:00-06:00 arası + 10.000 TL üzeri",
                            IsActive = true,
                            LogicalOperator = 1,
                            Name = "Gece Yüksek Tutar",
                            RuleType = 2
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000004"),
                            Code = "R004",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "Yüksek riskli üye işyeri kategori kodları",
                            IsActive = true,
                            LogicalOperator = 1,
                            Name = "Riskli MCC",
                            RuleType = 1
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000005"),
                            Code = "R005",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "Son 1 saatte aynı karttan 5+ işlem",
                            IsActive = true,
                            LogicalOperator = 1,
                            Name = "Saatlik Çok İşlem",
                            PeriodFunction = "COUNT",
                            PeriodGroupBy = "CARD",
                            PeriodMinutes = 60,
                            PeriodThreshold = 5m,
                            RuleType = 3
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000006"),
                            Code = "R006",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "Son 24 saatte 50.000 TL+ toplam işlem",
                            IsActive = true,
                            LogicalOperator = 1,
                            Name = "Günlük Yüksek Toplam",
                            PeriodFunction = "SUM",
                            PeriodGroupBy = "CARD",
                            PeriodMinutes = 1440,
                            PeriodThreshold = 50000m,
                            RuleType = 3
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000007"),
                            Code = "R007",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "PIN girilmemiş + 3.000 TL üzeri",
                            IsActive = true,
                            LogicalOperator = 1,
                            Name = "PIN'siz Yüksek Tutar",
                            RuleType = 2
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000008"),
                            Code = "F001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "100 TL altı işlemleri hariç tut",
                            IsActive = true,
                            LogicalOperator = 1,
                            Name = "Düşük Tutar Filtresi",
                            RuleType = 1
                        });
                });

            modelBuilder.Entity("Fraud.Domain.Entities.FraudRuleCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FraudRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Operator")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecondValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FraudRuleId");

                    b.ToTable("FraudRuleConditions", "fraud");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FraudRuleId = new Guid("a0000001-0000-0000-0000-000000000001"),
                            Operator = 3,
                            OrderIndex = 1,
                            ParameterName = "OriginalAmount",
                            Value = "25000"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FraudRuleId = new Guid("a0000001-0000-0000-0000-000000000002"),
                            Operator = 2,
                            OrderIndex = 1,
                            ParameterName = "MerchantCountryCode",
                            Value = "TR"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FraudRuleId = new Guid("a0000001-0000-0000-0000-000000000002"),
                            Operator = 3,
                            OrderIndex = 2,
                            ParameterName = "OriginalAmount",
                            Value = "5000"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FraudRuleId = new Guid("a0000001-0000-0000-0000-000000000003"),
                            Operator = 4,
                            OrderIndex = 1,
                            ParameterName = "TransactionHour",
                            Value = "2"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FraudRuleId = new Guid("a0000001-0000-0000-0000-000000000003"),
                            Operator = 6,
                            OrderIndex = 2,
                            ParameterName = "TransactionHour",
                            Value = "6"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FraudRuleId = new Guid("a0000001-0000-0000-0000-000000000003"),
                            Operator = 3,
                            OrderIndex = 3,
                            ParameterName = "OriginalAmount",
                            Value = "10000"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FraudRuleId = new Guid("a0000001-0000-0000-0000-000000000004"),
                            Operator = 9,
                            OrderIndex = 1,
                            ParameterName = "Mcc",
                            Value = "6051,6211,7995,5967,5966"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FraudRuleId = new Guid("a0000001-0000-0000-0000-000000000007"),
                            Operator = 1,
                            OrderIndex = 1,
                            ParameterName = "IsPinEntered",
                            Value = "False"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FraudRuleId = new Guid("a0000001-0000-0000-0000-000000000007"),
                            Operator = 3,
                            OrderIndex = 2,
                            ParameterName = "OriginalAmount",
                            Value = "3000"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FraudRuleId = new Guid("a0000001-0000-0000-0000-000000000008"),
                            Operator = 5,
                            OrderIndex = 1,
                            ParameterName = "OriginalAmount",
                            Value = "100"
                        });
                });

            modelBuilder.Entity("Fraud.Domain.Entities.FraudScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CheckMode")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FilterRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FraudResponseCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSimulation")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RunOrder")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioNo")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FilterRuleId");

                    b.HasIndex("IsActive");

                    b.HasIndex("RuleId");

                    b.HasIndex("ScenarioNo")
                        .IsUnique();

                    b.HasIndex("IsActive", "CheckMode");

                    b.ToTable("FraudScenarios", "fraud");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000001"),
                            CheckMode = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "25.000 TL üzeri tek işlem kontrolü",
                            FilterRuleId = new Guid("a0000001-0000-0000-0000-000000000008"),
                            FraudResponseCode = "05",
                            IsActive = true,
                            IsSimulation = false,
                            Name = "Yüksek Tutarlı İşlem Tespiti",
                            RuleId = new Guid("a0000001-0000-0000-0000-000000000001"),
                            RunOrder = 1,
                            ScenarioNo = 1,
                            Score = 70
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000002"),
                            CheckMode = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "Yurtdışı + yüksek tutar kombinasyonu",
                            FraudResponseCode = "01",
                            IsActive = true,
                            IsSimulation = false,
                            Name = "Yurtdışı Şüpheli İşlem",
                            RuleId = new Guid("a0000001-0000-0000-0000-000000000002"),
                            RunOrder = 2,
                            ScenarioNo = 2,
                            Score = 85
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000003"),
                            CheckMode = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "02-06 arası yüksek tutarlı işlem",
                            FraudResponseCode = "01",
                            IsActive = true,
                            IsSimulation = false,
                            Name = "Gece Saati Yüksek Tutar",
                            RuleId = new Guid("a0000001-0000-0000-0000-000000000003"),
                            RunOrder = 3,
                            ScenarioNo = 3,
                            Score = 80
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000004"),
                            CheckMode = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "Yüksek riskli MCC kodlarında işlem",
                            FilterRuleId = new Guid("a0000001-0000-0000-0000-000000000008"),
                            FraudResponseCode = "01",
                            IsActive = true,
                            IsSimulation = true,
                            Name = "Riskli Kategori İşlemi",
                            RuleId = new Guid("a0000001-0000-0000-0000-000000000004"),
                            RunOrder = 4,
                            ScenarioNo = 4,
                            Score = 60
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000005"),
                            CheckMode = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "Kısa sürede çok fazla işlem",
                            FraudResponseCode = "05",
                            IsActive = true,
                            IsSimulation = false,
                            Name = "Sıklık Anomalisi",
                            RuleId = new Guid("a0000001-0000-0000-0000-000000000005"),
                            RunOrder = 5,
                            ScenarioNo = 5,
                            Score = 90
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000006"),
                            CheckMode = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "24 saatte 50K+ toplam işlem",
                            FraudResponseCode = "01",
                            IsActive = true,
                            IsSimulation = false,
                            Name = "Günlük Limit Aşımı",
                            RuleId = new Guid("a0000001-0000-0000-0000-000000000006"),
                            RunOrder = 6,
                            ScenarioNo = 6,
                            Score = 75
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000007"),
                            CheckMode = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Description = "PIN doğrulaması olmadan yüksek tutar",
                            FraudResponseCode = "01",
                            IsActive = true,
                            IsSimulation = false,
                            Name = "PIN'siz Yüksek Tutar",
                            RuleId = new Guid("a0000001-0000-0000-0000-000000000007"),
                            RunOrder = 7,
                            ScenarioNo = 7,
                            Score = 65
                        });
                });

            modelBuilder.Entity("Fraud.Domain.Entities.HitScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("FraudResponseCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("FraudScenarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSimulation")
                        .HasColumnType("bit");

                    b.Property<string>("MaskedCardNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MerchantId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("FraudScenarioId");

                    b.HasIndex("MaskedCardNo");

                    b.HasIndex("TransactionId");

                    b.ToTable("HitScenarios", "fraud");
                });

            modelBuilder.Entity("Fraud.Domain.Entities.FraudAction", b =>
                {
                    b.HasOne("Fraud.Domain.Entities.FraudAlert", "FraudAlert")
                        .WithMany()
                        .HasForeignKey("FraudAlertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FraudAlert");
                });

            modelBuilder.Entity("Fraud.Domain.Entities.FraudRuleCondition", b =>
                {
                    b.HasOne("Fraud.Domain.Entities.FraudRule", "FraudRule")
                        .WithMany("Conditions")
                        .HasForeignKey("FraudRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FraudRule");
                });

            modelBuilder.Entity("Fraud.Domain.Entities.FraudScenario", b =>
                {
                    b.HasOne("Fraud.Domain.Entities.FraudRule", "FilterRule")
                        .WithMany()
                        .HasForeignKey("FilterRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fraud.Domain.Entities.FraudRule", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FilterRule");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Fraud.Domain.Entities.HitScenario", b =>
                {
                    b.HasOne("Fraud.Domain.Entities.FraudScenario", "FraudScenario")
                        .WithMany()
                        .HasForeignKey("FraudScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FraudScenario");
                });

            modelBuilder.Entity("Fraud.Domain.Entities.FraudRule", b =>
                {
                    b.Navigation("Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
