// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transaction.Infrastructure.Persistence;

#nullable disable

namespace Transaction.Infrastructure.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20260108175859_AddTransactionModule")]
    partial class AddTransactionModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Transaction.Domain.Entities.TransactionAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CardNumberEncrypted")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CardNumberMasked")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DeclineReason")
                        .HasColumnType("int")
                        .HasColumnName("DeclineReasonId");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FraudCheckResult")
                        .HasColumnType("int")
                        .HasColumnName("FraudCheckResultId");

                    b.Property<int?>("FraudScore")
                        .HasColumnType("int");

                    b.Property<string>("MerchantCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OriginalTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<string>("TerminalCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int")
                        .HasColumnName("TransactionTypeId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CardNumberMasked");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MerchantId");

                    b.HasIndex("OriginalTransactionId");

                    b.HasIndex("TerminalId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Transaction.Domain.Entities.TransactionAggregate", b =>
                {
                    b.OwnsOne("Transaction.Domain.ValueObjects.AuthorizationCode", "AuthorizationCode", b1 =>
                        {
                            b1.Property<Guid>("TransactionAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("nvarchar(6)")
                                .HasColumnName("AuthorizationCode");

                            b1.HasKey("TransactionAggregateId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionAggregateId");
                        });

                    b.OwnsOne("Transaction.Domain.ValueObjects.ReferenceNumber", "ReferenceNumber", b1 =>
                        {
                            b1.Property<Guid>("TransactionAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("ReferenceNumber");

                            b1.HasKey("TransactionAggregateId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionAggregateId");
                        });

                    b.OwnsOne("Transaction.Domain.ValueObjects.TransactionAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("TransactionAggregateId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionAggregateId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("AuthorizationCode");

                    b.Navigation("ReferenceNumber")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
