// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transaction.Infrastructure.Persistence;

#nullable disable

namespace Transaction.Infrastructure.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20260214102833_AddCardLimitDefinitions")]
    partial class AddCardLimitDefinitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Transaction.Domain.Entities.CardLimitDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("DailyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LimitType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("MonthlyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SingleTransactionLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TargetValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("LimitType", "TargetValue")
                        .IsUnique()
                        .HasFilter("[TargetValue] IS NOT NULL");

                    b.ToTable("CardLimitDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Currency = "TRY",
                            DailyLimit = 10000m,
                            Description = "Sistem varsayılan limiti",
                            IsActive = true,
                            LimitType = "DEFAULT",
                            MonthlyLimit = 50000m,
                            SingleTransactionLimit = 5000m
                        });
                });

            modelBuilder.Entity("Transaction.Domain.Entities.TransactionAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CardNumberEncrypted")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CardNumberMasked")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DeclineReason")
                        .HasColumnType("int")
                        .HasColumnName("DeclineReasonId");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FraudCheckResult")
                        .HasColumnType("int")
                        .HasColumnName("FraudCheckResultId");

                    b.Property<int?>("FraudScore")
                        .HasColumnType("int");

                    b.Property<string>("MerchantCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OriginalTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<string>("TerminalCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int")
                        .HasColumnName("TransactionTypeId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CardNumberMasked")
                        .HasDatabaseName("IX_Transactions_CardNumberMasked");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Transactions_CreatedAt");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("IX_Transactions_MerchantId");

                    b.HasIndex("OriginalTransactionId")
                        .HasDatabaseName("IX_Transactions_OriginalTransactionId");

                    b.HasIndex("TerminalId")
                        .HasDatabaseName("IX_Transactions_TerminalId");

                    b.HasIndex("BatchNumber", "Status")
                        .HasDatabaseName("IX_Transactions_BatchNumber_Status")
                        .HasFilter("[BatchNumber] IS NOT NULL");

                    b.HasIndex("CardNumberMasked", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Transactions_CardNumber_CreatedAt");

                    b.HasIndex("MerchantId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Transactions_MerchantId_CreatedAt");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Transactions_Status_CreatedAt");

                    b.HasIndex("TerminalId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Transactions_TerminalId_CreatedAt");

                    b.HasIndex("CreatedAt", "Status", "TransactionType")
                        .HasDatabaseName("IX_Transactions_Date_Status_Type");

                    b.HasIndex("CardNumberMasked", "Status", "TransactionType", "CreatedAt")
                        .HasDatabaseName("IX_Transactions_Card_Status_Type_Date");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Transaction.Domain.Entities.TransactionAggregate", b =>
                {
                    b.OwnsOne("Transaction.Domain.ValueObjects.AuthorizationCode", "AuthorizationCode", b1 =>
                        {
                            b1.Property<Guid>("TransactionAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("nvarchar(6)")
                                .HasColumnName("AuthorizationCode");

                            b1.HasKey("TransactionAggregateId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionAggregateId");
                        });

                    b.OwnsOne("Transaction.Domain.ValueObjects.ReferenceNumber", "ReferenceNumber", b1 =>
                        {
                            b1.Property<Guid>("TransactionAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("ReferenceNumber");

                            b1.HasKey("TransactionAggregateId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionAggregateId");
                        });

                    b.OwnsOne("Transaction.Domain.ValueObjects.TransactionAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("TransactionAggregateId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionAggregateId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("AuthorizationCode");

                    b.Navigation("ReferenceNumber")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
