<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Card.Application\Card.Application.csproj" />
    <ProjectReference Include="..\Card.Domain\Card.Domain.csproj" />
    <ProjectReference Include="..\Card.Infrastructure\Card.Infrastructure.csproj" />
    <ProjectReference Include="..\CardMerchantSystem.Shared\CardMerchantSystem.Shared.csproj" />
    <ProjectReference Include="..\Merchant.Application\Merchant.Application.csproj" />
    <ProjectReference Include="..\Merchant.Domain\Merchant.Domain.csproj" />
    <ProjectReference Include="..\Merchant.Infrastructure\Merchant.Infrastructure.csproj" />
  </ItemGroup>

</Project>
