<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.9" />
    <PackageReference Include="Hangfire.Core" Version="1.8.9" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.9" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Accounting.Application\Accounting.Application.csproj" />
    <ProjectReference Include="..\Accounting.Domain\Accounting.Domain.csproj" />
    <ProjectReference Include="..\Accounting.Infrastructure\Accounting.Infrastructure.csproj" />
    <ProjectReference Include="..\BKM.Application\BKM.Application.csproj" />
    <ProjectReference Include="..\BKM.Domain\BKM.Domain.csproj" />
    <ProjectReference Include="..\BKM.Infrastructure\BKM.Infrastructure.csproj" />
    <ProjectReference Include="..\Campaign.Application\Campaign.Application.csproj" />
    <ProjectReference Include="..\Campaign.Domain\Campaign.Domain.csproj" />
    <ProjectReference Include="..\Campaign.Infrastructure\Campaign.Infrastructure.csproj" />
    <ProjectReference Include="..\Card.Application\Card.Application.csproj" />
    <ProjectReference Include="..\Card.Domain\Card.Domain.csproj" />
    <ProjectReference Include="..\Card.Infrastructure\Card.Infrastructure.csproj" />
    <ProjectReference Include="..\CardMerchantSystem.Shared\CardMerchantSystem.Shared.csproj" />
    <ProjectReference Include="..\Dispute.Application\Dispute.Application.csproj" />
    <ProjectReference Include="..\Dispute.Domain\Dispute.Domain.csproj" />
    <ProjectReference Include="..\Dispute.Infrastructure\Dispute.Infrastructure.csproj" />
    <ProjectReference Include="..\Fee.Application\Fee.Application.csproj" />
    <ProjectReference Include="..\Fee.Domain\Fee.Domain.csproj" />
    <ProjectReference Include="..\Fee.Infrastructure\Fee.Infrastructure.csproj" />
    <ProjectReference Include="..\HSM.Application\HSM.Application.csproj" />
    <ProjectReference Include="..\HSM.Domain\HSM.Domain.csproj" />
    <ProjectReference Include="..\HSM.Infrastructure\HSM.Infrastructure.csproj" />
    <ProjectReference Include="..\Merchant.Application\Merchant.Application.csproj" />
    <ProjectReference Include="..\Merchant.Domain\Merchant.Domain.csproj" />
    <ProjectReference Include="..\Merchant.Infrastructure\Merchant.Infrastructure.csproj" />
    <ProjectReference Include="..\MerchantReport.Application\MerchantReport.Application.csproj" />
    <ProjectReference Include="..\MerchantReport.Domain\MerchantReport.Domain.csproj" />
    <ProjectReference Include="..\MerchantReport.Infrastructure\MerchantReport.Infrastructure.csproj" />
    <ProjectReference Include="..\Statement.Application\Statement.Application.csproj" />
    <ProjectReference Include="..\Statement.Domain\Statement.Domain.csproj" />
    <ProjectReference Include="..\Statement.Infrastructure\Statement.Infrastructure.csproj" />
    <ProjectReference Include="..\Transaction.Application\Transaction.Application.csproj" />
    <ProjectReference Include="..\Transaction.Domain\Transaction.Domain.csproj" />
    <ProjectReference Include="..\Transaction.Infrastructure\Transaction.Infrastructure.csproj" />
  </ItemGroup>

</Project>
