// <auto-generated />
using System;
using Merchant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Merchant.Infrastructure.Persistence.Migrations.PostgreSql
{
    [DbContext(typeof(MerchantDbContext_Pg))]
    [Migration("20260127191429_InitialCreate_PostgreSql")]
    partial class InitialCreate_PostgreSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Merchant.Domain.Entities.MerchantAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MerchantType")
                        .HasColumnType("integer")
                        .HasColumnName("MerchantTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("StatusId");

                    b.Property<string>("TaxOffice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.ToTable("Merchants", "public");
                });

            modelBuilder.Entity("Merchant.Domain.Entities.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("InstalledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InstalledBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("StatusId");

                    b.Property<int>("TerminalType")
                        .HasColumnType("integer")
                        .HasColumnName("TerminalTypeId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MerchantId");

                    b.HasIndex("Status");

                    b.ToTable("Terminals", "public");
                });

            modelBuilder.Entity("Merchant.Domain.Entities.MerchantAggregate", b =>
                {
                    b.OwnsOne("Merchant.Domain.ValueObjects.IBAN", "IBAN", b1 =>
                        {
                            b1.Property<Guid>("MerchantAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(26)
                                .HasColumnType("character varying(26)")
                                .HasColumnName("IBAN");

                            b1.HasKey("MerchantAggregateId");

                            b1.ToTable("Merchants", "public");

                            b1.WithOwner()
                                .HasForeignKey("MerchantAggregateId");
                        });

                    b.OwnsOne("Merchant.Domain.ValueObjects.MerchantCode", "MerchantCode", b1 =>
                        {
                            b1.Property<Guid>("MerchantAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("MerchantCode");

                            b1.HasKey("MerchantAggregateId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Merchants", "public");

                            b1.WithOwner()
                                .HasForeignKey("MerchantAggregateId");
                        });

                    b.OwnsOne("Merchant.Domain.ValueObjects.TaxNumber", "TaxNumber", b1 =>
                        {
                            b1.Property<Guid>("MerchantAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("TaxNumber");

                            b1.HasKey("MerchantAggregateId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Merchants", "public");

                            b1.WithOwner()
                                .HasForeignKey("MerchantAggregateId");
                        });

                    b.Navigation("IBAN")
                        .IsRequired();

                    b.Navigation("MerchantCode")
                        .IsRequired();

                    b.Navigation("TaxNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Merchant.Domain.Entities.Terminal", b =>
                {
                    b.HasOne("Merchant.Domain.Entities.MerchantAggregate", null)
                        .WithMany("Terminals")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Merchant.Domain.ValueObjects.TerminalId", "TerminalCode", b1 =>
                        {
                            b1.Property<Guid>("TerminalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("TerminalCode");

                            b1.HasKey("TerminalId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Terminals", "public");

                            b1.WithOwner()
                                .HasForeignKey("TerminalId");
                        });

                    b.Navigation("TerminalCode")
                        .IsRequired();
                });

            modelBuilder.Entity("Merchant.Domain.Entities.MerchantAggregate", b =>
                {
                    b.Navigation("Terminals");
                });
#pragma warning restore 612, 618
        }
    }
}
