// <auto-generated />
using System;
using CardMerchantSystem.API.Auth.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardMerchantSystem.API.Auth.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260121111015_InitAuthModule")]
    partial class InitAuthModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AuthRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tüm sistem yetkilerine sahip",
                            DisplayName = "Sistem Yöneticisi",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kart operasyonları yönetimi",
                            DisplayName = "Kart Operasyon",
                            Name = "CardOperator"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Üye işyeri operasyonları yönetimi",
                            DisplayName = "Üye İşyeri Operasyon",
                            Name = "MerchantOperator"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Finansal işlemler yönetimi",
                            DisplayName = "Finans Operasyon",
                            Name = "FinanceOperator"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Uyum ve yasal raporlama",
                            DisplayName = "Uyum Sorumlusu",
                            Name = "ComplianceOfficer"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Çağrı merkezi işlemleri",
                            DisplayName = "Çağrı Merkezi",
                            Name = "CallCenterAgent"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sadece görüntüleme yetkisi",
                            DisplayName = "Görüntüleyici",
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AuthUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@cardmerchant.com",
                            FullName = "Sistem Yöneticisi",
                            IsActive = true,
                            PasswordHash = "$2a$11$Z7KS61.O8dmAgNBto1VyROa0jVoe5qlm2RVOj2wEpMdAXzY.aVoMW",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AuthUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleId = 1,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AssignedBy = "System"
                        });
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("CardMerchantSystem.API.Auth.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardMerchantSystem.API.Auth.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
