// <auto-generated />
using System;
using CardMerchantSystem.API.Auth.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardMerchantSystem.API.Auth.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260122142911_AddLanguageTables")]
    partial class AddLanguageTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.LanguageEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "tr",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            Name = "Turkish",
                            NativeName = "Türkçe"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "English",
                            NativeName = "English"
                        });
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.MenuClaimEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MenuId", "ClaimType", "ClaimValue")
                        .IsUnique();

                    b.ToTable("AuthMenuClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            ClaimType = "Policy",
                            ClaimValue = "ViewerOrAbove",
                            MenuId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            ClaimType = "Policy",
                            ClaimValue = "CardManagement",
                            MenuId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            ClaimType = "Policy",
                            ClaimValue = "CardManagement",
                            MenuId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            ClaimType = "Policy",
                            ClaimValue = "CardManagement",
                            MenuId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            ClaimType = "Policy",
                            ClaimValue = "CardManagement",
                            MenuId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            ClaimType = "Policy",
                            ClaimValue = "MerchantManagement",
                            MenuId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            ClaimType = "Policy",
                            ClaimValue = "MerchantManagement",
                            MenuId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            ClaimType = "Policy",
                            ClaimValue = "MerchantManagement",
                            MenuId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            ClaimType = "Policy",
                            ClaimValue = "FinanceManagement",
                            MenuId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            ClaimType = "Policy",
                            ClaimValue = "FinanceManagement",
                            MenuId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            ClaimType = "Policy",
                            ClaimValue = "FinanceManagement",
                            MenuId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000012"),
                            ClaimType = "Policy",
                            ClaimValue = "FinanceManagement",
                            MenuId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000013"),
                            ClaimType = "Policy",
                            ClaimValue = "WorkOrderManagement",
                            MenuId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000014"),
                            ClaimType = "Policy",
                            ClaimValue = "AdminOnly",
                            MenuId = new Guid("10000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000015"),
                            ClaimType = "Policy",
                            ClaimValue = "AdminOnly",
                            MenuId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000016"),
                            ClaimType = "Policy",
                            ClaimValue = "AdminOnly",
                            MenuId = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000017"),
                            ClaimType = "Policy",
                            ClaimValue = "AdminOnly",
                            MenuId = new Guid("20000000-0000-0000-0000-000000000011")
                        });
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.MenuEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("AuthMenus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Icon = "layout-dashboard",
                            IsActive = true,
                            IsVisible = true,
                            Name = "dashboard",
                            Path = "/dashboard",
                            Title = "Dashboard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Icon = "credit-card",
                            IsActive = true,
                            IsVisible = true,
                            Name = "card-management",
                            Title = "Kart Yönetimi"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Icon = "credit-card",
                            IsActive = true,
                            IsVisible = true,
                            Name = "cards",
                            ParentId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Path = "/cards",
                            Title = "Kartlar"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Icon = "file-text",
                            IsActive = true,
                            IsVisible = true,
                            Name = "card-applications",
                            ParentId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Path = "/card-applications",
                            Title = "Başvurular"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Icon = "shield-off",
                            IsActive = true,
                            IsVisible = true,
                            Name = "card-blocks",
                            ParentId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Path = "/card-blocks",
                            Title = "Blokeler"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Icon = "store",
                            IsActive = true,
                            IsVisible = true,
                            Name = "merchant-management",
                            Title = "Üye İşyeri"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Icon = "building",
                            IsActive = true,
                            IsVisible = true,
                            Name = "merchants",
                            ParentId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Path = "/merchants",
                            Title = "İşyerleri"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Icon = "monitor",
                            IsActive = true,
                            IsVisible = true,
                            Name = "terminals",
                            ParentId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Path = "/terminals",
                            Title = "Terminaller"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            Icon = "wallet",
                            IsActive = true,
                            IsVisible = true,
                            Name = "finance-management",
                            Title = "Finans"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Icon = "arrow-left-right",
                            IsActive = true,
                            IsVisible = true,
                            Name = "transactions",
                            ParentId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Path = "/transactions",
                            Title = "İşlemler"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Icon = "file-spreadsheet",
                            IsActive = true,
                            IsVisible = true,
                            Name = "statements",
                            ParentId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Path = "/statements",
                            Title = "Ekstreler"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Icon = "calculator",
                            IsActive = true,
                            IsVisible = true,
                            Name = "accounting",
                            ParentId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Path = "/accounting",
                            Title = "Muhasebe"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            Icon = "clipboard-list",
                            IsActive = true,
                            IsVisible = true,
                            Name = "work-orders",
                            Path = "/work-orders",
                            Title = "İş Emirleri"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            Icon = "settings",
                            IsActive = true,
                            IsVisible = true,
                            Name = "system-management",
                            Title = "Sistem"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Icon = "users",
                            IsActive = true,
                            IsVisible = true,
                            Name = "users",
                            ParentId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Path = "/users",
                            Title = "Kullanıcılar"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Icon = "shield",
                            IsActive = true,
                            IsVisible = true,
                            Name = "roles",
                            ParentId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Path = "/roles",
                            Title = "Roller"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Icon = "menu",
                            IsActive = true,
                            IsVisible = true,
                            Name = "menus",
                            ParentId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Path = "/menus",
                            Title = "Menüler"
                        });
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AuthRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tüm sistem yetkilerine sahip",
                            DisplayName = "Sistem Yöneticisi",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kart operasyonları yönetimi",
                            DisplayName = "Kart Operasyon",
                            Name = "CardOperator"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Üye işyeri operasyonları yönetimi",
                            DisplayName = "Üye İşyeri Operasyon",
                            Name = "MerchantOperator"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Finansal işlemler yönetimi",
                            DisplayName = "Finans Operasyon",
                            Name = "FinanceOperator"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Uyum ve yasal raporlama",
                            DisplayName = "Uyum Sorumlusu",
                            Name = "ComplianceOfficer"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Çağrı merkezi işlemleri",
                            DisplayName = "Çağrı Merkezi",
                            Name = "CallCenterAgent"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sadece görüntüleme yetkisi",
                            DisplayName = "Görüntüleyici",
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.TranslationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("LanguageEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("LanguageEntityId");

                    b.HasIndex("LanguageCode", "Key")
                        .IsUnique();

                    b.ToTable("Translations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000001"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.dashboard",
                            LanguageCode = "tr",
                            Value = "Dashboard"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000002"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.card-management",
                            LanguageCode = "tr",
                            Value = "Kart Yönetimi"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000003"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.cards",
                            LanguageCode = "tr",
                            Value = "Kartlar"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000004"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.card-applications",
                            LanguageCode = "tr",
                            Value = "Başvurular"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000005"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.card-blocks",
                            LanguageCode = "tr",
                            Value = "Blokeler"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000006"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.merchant-management",
                            LanguageCode = "tr",
                            Value = "Üye İşyeri"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000007"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.merchants",
                            LanguageCode = "tr",
                            Value = "İşyerleri"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000008"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.terminals",
                            LanguageCode = "tr",
                            Value = "Terminaller"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000009"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.finance-management",
                            LanguageCode = "tr",
                            Value = "Finans"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000010"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.transactions",
                            LanguageCode = "tr",
                            Value = "İşlemler"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000011"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.statements",
                            LanguageCode = "tr",
                            Value = "Ekstreler"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000012"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.accounting",
                            LanguageCode = "tr",
                            Value = "Muhasebe"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000013"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.work-orders",
                            LanguageCode = "tr",
                            Value = "İş Emirleri"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000014"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.system-management",
                            LanguageCode = "tr",
                            Value = "Sistem"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000015"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.users",
                            LanguageCode = "tr",
                            Value = "Kullanıcılar"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000016"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.roles",
                            LanguageCode = "tr",
                            Value = "Roller"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0001-000000000017"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.menus",
                            LanguageCode = "tr",
                            Value = "Menüler"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000001"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.dashboard",
                            LanguageCode = "en",
                            Value = "Dashboard"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000002"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.card-management",
                            LanguageCode = "en",
                            Value = "Card Management"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000003"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.cards",
                            LanguageCode = "en",
                            Value = "Cards"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000004"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.card-applications",
                            LanguageCode = "en",
                            Value = "Applications"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000005"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.card-blocks",
                            LanguageCode = "en",
                            Value = "Blocks"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000006"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.merchant-management",
                            LanguageCode = "en",
                            Value = "Merchant"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000007"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.merchants",
                            LanguageCode = "en",
                            Value = "Merchants"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000008"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.terminals",
                            LanguageCode = "en",
                            Value = "Terminals"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000009"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.finance-management",
                            LanguageCode = "en",
                            Value = "Finance"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000010"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.transactions",
                            LanguageCode = "en",
                            Value = "Transactions"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000011"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.statements",
                            LanguageCode = "en",
                            Value = "Statements"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000012"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.accounting",
                            LanguageCode = "en",
                            Value = "Accounting"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000013"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.work-orders",
                            LanguageCode = "en",
                            Value = "Work Orders"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000014"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.system-management",
                            LanguageCode = "en",
                            Value = "System"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000015"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.users",
                            LanguageCode = "en",
                            Value = "Users"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000016"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.roles",
                            LanguageCode = "en",
                            Value = "Roles"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0002-000000000017"),
                            Category = "menu",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "menu.menus",
                            LanguageCode = "en",
                            Value = "Menus"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0003-000000000001"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.Admin",
                            LanguageCode = "tr",
                            Value = "Sistem Yöneticisi"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0003-000000000002"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.CardOperator",
                            LanguageCode = "tr",
                            Value = "Kart Operasyon"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0003-000000000003"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.MerchantOperator",
                            LanguageCode = "tr",
                            Value = "Üye İşyeri Operasyon"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0003-000000000004"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.FinanceOperator",
                            LanguageCode = "tr",
                            Value = "Finans Operasyon"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0003-000000000005"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.ComplianceOfficer",
                            LanguageCode = "tr",
                            Value = "Uyum Sorumlusu"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0003-000000000006"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.CallCenterAgent",
                            LanguageCode = "tr",
                            Value = "Çağrı Merkezi"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0003-000000000007"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.Viewer",
                            LanguageCode = "tr",
                            Value = "Görüntüleyici"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0004-000000000001"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.Admin",
                            LanguageCode = "en",
                            Value = "System Administrator"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0004-000000000002"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.CardOperator",
                            LanguageCode = "en",
                            Value = "Card Operator"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0004-000000000003"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.MerchantOperator",
                            LanguageCode = "en",
                            Value = "Merchant Operator"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0004-000000000004"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.FinanceOperator",
                            LanguageCode = "en",
                            Value = "Finance Operator"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0004-000000000005"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.ComplianceOfficer",
                            LanguageCode = "en",
                            Value = "Compliance Officer"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0004-000000000006"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.CallCenterAgent",
                            LanguageCode = "en",
                            Value = "Call Center Agent"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0004-000000000007"),
                            Category = "role",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "role.Viewer",
                            LanguageCode = "en",
                            Value = "Viewer"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000001"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.save",
                            LanguageCode = "tr",
                            Value = "Kaydet"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000002"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.cancel",
                            LanguageCode = "tr",
                            Value = "İptal"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000003"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.delete",
                            LanguageCode = "tr",
                            Value = "Sil"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000004"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.edit",
                            LanguageCode = "tr",
                            Value = "Düzenle"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000005"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.add",
                            LanguageCode = "tr",
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000006"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.search",
                            LanguageCode = "tr",
                            Value = "Ara"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000007"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.filter",
                            LanguageCode = "tr",
                            Value = "Filtrele"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000008"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.refresh",
                            LanguageCode = "tr",
                            Value = "Yenile"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000009"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.yes",
                            LanguageCode = "tr",
                            Value = "Evet"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000010"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.no",
                            LanguageCode = "tr",
                            Value = "Hayır"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000011"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.loading",
                            LanguageCode = "tr",
                            Value = "Yükleniyor..."
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000012"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.noData",
                            LanguageCode = "tr",
                            Value = "Veri bulunamadı"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000013"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.success",
                            LanguageCode = "tr",
                            Value = "Başarılı"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000014"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.error",
                            LanguageCode = "tr",
                            Value = "Hata"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000015"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.warning",
                            LanguageCode = "tr",
                            Value = "Uyarı"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000016"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.confirm",
                            LanguageCode = "tr",
                            Value = "Onayla"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000017"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.back",
                            LanguageCode = "tr",
                            Value = "Geri"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000018"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.next",
                            LanguageCode = "tr",
                            Value = "İleri"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000019"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.close",
                            LanguageCode = "tr",
                            Value = "Kapat"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0005-000000000020"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.actions",
                            LanguageCode = "tr",
                            Value = "İşlemler"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000001"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.save",
                            LanguageCode = "en",
                            Value = "Save"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000002"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.cancel",
                            LanguageCode = "en",
                            Value = "Cancel"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000003"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.delete",
                            LanguageCode = "en",
                            Value = "Delete"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000004"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.edit",
                            LanguageCode = "en",
                            Value = "Edit"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000005"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.add",
                            LanguageCode = "en",
                            Value = "Add"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000006"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.search",
                            LanguageCode = "en",
                            Value = "Search"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000007"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.filter",
                            LanguageCode = "en",
                            Value = "Filter"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000008"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.refresh",
                            LanguageCode = "en",
                            Value = "Refresh"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000009"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.yes",
                            LanguageCode = "en",
                            Value = "Yes"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000010"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.no",
                            LanguageCode = "en",
                            Value = "No"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000011"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.loading",
                            LanguageCode = "en",
                            Value = "Loading..."
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000012"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.noData",
                            LanguageCode = "en",
                            Value = "No data found"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000013"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.success",
                            LanguageCode = "en",
                            Value = "Success"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000014"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.error",
                            LanguageCode = "en",
                            Value = "Error"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000015"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.warning",
                            LanguageCode = "en",
                            Value = "Warning"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000016"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.confirm",
                            LanguageCode = "en",
                            Value = "Confirm"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000017"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.back",
                            LanguageCode = "en",
                            Value = "Back"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000018"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.next",
                            LanguageCode = "en",
                            Value = "Next"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000019"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.close",
                            LanguageCode = "en",
                            Value = "Close"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0006-000000000020"),
                            Category = "common",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "common.actions",
                            LanguageCode = "en",
                            Value = "Actions"
                        });
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AuthUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@cardmerchant.com",
                            FullName = "Sistem Yöneticisi",
                            IsActive = true,
                            PasswordHash = "$2a$11$933PXijjtQ1qhyz1gyxAOub8lC.TfyOgvLT1CpsPCOp70e7kq5cIa",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AuthUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleId = 1,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AssignedBy = "System"
                        });
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.MenuClaimEntity", b =>
                {
                    b.HasOne("CardMerchantSystem.API.Auth.Entities.MenuEntity", "Menu")
                        .WithMany("Claims")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.MenuEntity", b =>
                {
                    b.HasOne("CardMerchantSystem.API.Auth.Entities.MenuEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.TranslationEntity", b =>
                {
                    b.HasOne("CardMerchantSystem.API.Auth.Entities.LanguageEntity", null)
                        .WithMany("Translations")
                        .HasForeignKey("LanguageEntityId");
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("CardMerchantSystem.API.Auth.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardMerchantSystem.API.Auth.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.LanguageEntity", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.MenuEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Claims");
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CardMerchantSystem.API.Auth.Entities.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
